# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='otherinfo',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='OtherInfo',
        ),
    ]
