# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='ProfilePic/')),
            ],
            options={
                'db_table': 'profilePic',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='RestaurantImage/')),
            ],
            options={
                'db_table': 'restaurantImage',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Image/'),
        ),
    ]
