# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20180107_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='user',
        ),
    ]
