# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20180104_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant')),
            ],
            options={
                'db_table': 'otherInfo',
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.AppUser')),
            ],
            options={
                'db_table': 'participate',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.AppUser')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant')),
            ],
            options={
                'db_table': 'gathering',
            },
        ),
    ]
