# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_otherinfo_participate_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profilePic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.ProfilePic'),
        ),
    ]
