# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_profilepic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='password',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='gathering',
            name='member',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='self_introduction',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='average_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gathering',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
