# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20180107_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profilePic',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
