# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_appuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gathering',
            name='created_by',
        ),
        migrations.AddField(
            model_name='gathering',
            name='member',
            field=models.ManyToManyField(through='API.Participate', to='API.AppUser'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='self_introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participate',
            name='gathering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Gathering'),
        ),
    ]
