# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20180104_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='joined_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
