# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0009_auto_20180107_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='id',
        ),
        migrations.AddField(
            model_name='gathering',
            name='member',
            field=models.ManyToManyField(related_name='joined', through='API.Participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.Restaurant'),
        ),
    ]
