# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0010_auto_20180107_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ManyToManyField(related_name='enjoy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RestaurantImage',
        ),
    ]
