# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20180111_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='RestaurantImage/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Restaurant')),
            ],
            options={
                'db_table': 'restaurantImage',
            },
        ),
    ]
