# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_restaurantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Images/None/No-img.jpg', upload_to='ProfilePic/'),
        ),
    ]
