# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Images/None/No-img.jpg', null=True, upload_to='ProfilePic/'),
        ),
    ]
