# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0014_auto_20180114_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gathering',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='owner',
            field=models.ManyToManyField(related_name='enjoy', to=settings.AUTH_USER_MODEL),
        ),
    ]
