# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20180114_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='owner',
            new_name='user',
        ),
    ]
