# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20180114_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gathering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
