# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20180115_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default='ProfilePic/default.png', upload_to='ProfilePic/'),
        ),
    ]
