# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20180120_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='ProfilePic/default.png', null=True, upload_to='ProfilePic/'),
        ),
    ]
