# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20180120_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='API.Restaurant'),
        ),
    ]
