# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_recommendedrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedrate',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
