# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_recommendedrate_gathering'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cluster',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
