# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_profile_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedrate',
            name='rating',
        ),
        migrations.AddField(
            model_name='recommendedrate',
            name='cluster_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendedrate',
            name='restaurant_rate',
            field=models.FloatField(default=0),
        ),
    ]
