# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20180312_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedrate',
            name='restaurant',
        ),
    ]
