# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_recommendedrate_distance_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
