# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_auto_20180318_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='created',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_range',
            field=models.IntegerField(default=0),
        ),
    ]
