# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
